### ISSUE TITLE
Errors 

### ISSUE THREAD

**Issue by shaoyoucheng** [amarinderthind/mutation_load_comparison_plot#1]
Input:
#library(plyr)
##tt <- count(ID9$Cancer.Types)
tt<- tt[match(cancers, tt$Var1),]
####################################

Output:
tt
      Cancer.Types Freq
NA            <NA>   NA
NA.1          <NA>   NA
NA.2          <NA>   NA
NA.3          <NA>   NA
NA.4          <NA>   NA
NA.5          <NA>   NA
NA.6          <NA>   NA
NA.7          <NA>   NA
NA.8          <NA>   NA
NA.9          <NA>   NA
NA.10         <NA>   NA
NA.11         <NA>   NA
NA.12         <NA>   NA
NA.13         <NA>   NA
NA.14         <NA>   NA
NA.15         <NA>   NA
NA.16         <NA>   NA
NA.17         <NA>   NA
NA.18         <NA>   NA
NA.19         <NA>   NA
NA.20         <NA>   NA

**Comment by amarinderthind** [comment]
Check the new script, I updated

**Comment by shaoyoucheng** [comment]
thanks for your generous help
